- lib/oeqa/runtime/nodejs/apprt_nodejs_runtime.py
- lib/oeqa/runtime/nodejs/apprt_nodejs_runtime_log_parser.py
- lib/oeqa/runtime/nodejs/files/noderuntime/apprt_nodejs_runtime_config
The test is from https://github.com/nodejs/node, all test cases included under the 'test' directory,
the case name is composed the sub-directory of 'test' and the file name under sub-directory, omit the file suffix.
The test case number is same as manually run tests on device.
Image build#368.
Related to: IOTOS-1131
Signed-off-by: Wang Hongjuan <hongjuanx.wang@intel.com>
> [nodejs] Fix issue that the test cases name are same as

- lib/runtest.py
add RuntestTestContext and copy some code from runexport.py to avoid some
import issue
> meta-iotqa: a work around methods to fit upstream changes

- lib/oeqa/runtime/ethernet/files/ipv6_ssh.exp
When device image is rebuilt, the original ssh key in host will
have conflict. Add ssh options to avoid this.
> ethernet: add ssh options to avoid conflicting key

- conf/test/security.manifest
Adding oeqa.runtime.ima to security.manifest
IMA tests can be found in github.com/01org/meta-intel-iot-security,
path meta-integrity/lib/oeqa/runtime/ima.py
> security.manifest: add IMA tests

- lib/oeqa/runtime/security/dac_config.py
- lib/oeqa/runtime/security/firewall_rules.py
Fix error checking in dac_config and firewall_rules so that tests
fail when device is disconnected. Check by error expected, not by
exit code, since that will always be non-zero if ssh fails.
> security tests: error checking for tests with device disconnected

- lib/oeqa/runtime/iotivity/iotvt_integration.py
Recent discoverid case has some changes in output, which will make
automation case check fail (actually case should pass). Modify the check points.
> iotivity: modify output of the descoverid case

- lib/oeqa/runtime/security/firewall_rules.py
Previously, the test assumed only 1 ipv6 connection for the host.
Now, it gets the ipv6 address assigned to the interface with
$SERVER_IP.
> firewall_rules.py: fix outgoing ipv6 test

- lib/oeqa/runtime/bluetooth/bluetooth.py
- lib/oeqa/runtime/bluetooth/comm_bt_6lowpan.py
- lib/oeqa/runtime/bluetooth/comm_bt_command.py
Add 2 cases to fill origin feature gaps.
Add 2 basic checking cases for 6lowpan over BLE.
> comm_bluetooth: add 4 cases to Bluetooth component

- conf/test/manual.csv
Since swupd feature won't be supported in M4, change the test_swupd_remote
back to design status and skip execution.
[Related-to]: IOTOS-970
[skip ci]
Signed-off-by: ma yan <yan.ma@intel.com>
> swupd: update remote swupd TC to design status

- conf/test/zigbee.manifest
- lib/oeqa/runtime/zigbee/comm_zigbee_basic.py
- lib/oeqa/runtime/zigbee/zigbee.py
Add one 802.15.4 case to check inserting 80.15.4 module.
This case is only runable on Galileo and MinnowMax platform.
> 802.15.4: add 1 802.15.4 case for sanity check

- conf/test/stability.manifest
- lib/oeqa/runtime/appfw/test_appfw.py
- lib/oeqa/runtime/appfw/test_appfw_stability.py
Add 2 stability cases for start/stop node/python runtime app many times
Add related manifest entry for stability cases
Add auto case for IOTOS-358
> appfw test cases: optimize code for stability case reuse

- conf/test/galileo.fullauto.manifest
- conf/test/minnowmax.fullauto.manifest
- conf/test/zigbee.manifest
- lib/oeqa/runtime/zigbee/comm_zigbee_cc2520.py
- lib/oeqa/runtime/zigbee/comm_zigbee_mnode.py
- lib/oeqa/runtime/zigbee/zigbee.py
Add two cases for zigbee check:
One is for cc2520 module insert (only for MinnowMax)
The other is for atmel zigbee ping between 2 IoT devices.
> zigbee: add 1 cc2520 case and 1 zigbee ping case

- lib/oeqa/runtime/iotivity/iotvt_integration.py
- lib/oeqa/runtime/sanity/iotivity.py
Add 1 FVT case (negative) to run iotivity test by root account, it should fail as IOTOS-1004 asks to forbid root account.
Change all the other original 16 integration cases to run by non-root user.
> iotivity: add 1 FVT case for IOTOS-1004 and use non-root to run others

- conf/test/manual.csv
Added testcases covering secureboot: correctly signed image,
unsigned image, different key signed image. Based on the uefi
secure boot documentation provided in meta-ostro/doc/howtos
> manual.csv: add secure boot testcase

- conf/test/bsp.manifest
remove empty line in manifest file, otherwise the runner will fail to run.
workaround of bug IOTOS-1447
> bsp.manifest: remove empty line in manifest file

- lib/oeqa/utils/helper.py
run_as use {su username -c "cmd"} to run a cmd as username, but when cmd has some characters such as " and $, these character need escape for keep original meaning.
> meta-iotqa: fix a bug in run_as

- recipes-core/packagegroups/packagegroup-qa-tests.bb
- recipes-test/appfw-test-app/appfw-test-app.bb
- recipes-test/appfw-test-app/files/COPYING.MIT
- recipes-test/appfw-test-app/files/manifest
- recipes-test/appfw-test-app/files/wrapperapp
The wrapperapp is a shell script, so can use/modify it for more test cases.
> meta-iotqa: add qa test app for appfw

- lib/oeqa/runtime/iotivity/iotvt_integration.py
- lib/oeqa/runtime/iotivity/iotvt_integration_mnode.py
- lib/oeqa/runtime/iotivity/iotvt_wifi.py
- lib/oeqa/runtime/sanity/iotivity.py
Modify 4 sanity iotivity to  root account usage.
Add 13 sample app cases on two Ostro devices via ethernet.
Enable 4 iotivity cases on two Ostro devices via WiFi.
> iotivity: modify 4 sanity cases and add 17 cases on multiple devices

- classes/test-iot.bbclass
- recipes-image/images/ostro-image.bbappend
This was used already successfully in
https://github.com/ostroproject/ostro-os/pull/25 to build and sanity
test swupd-enabled images. The extra dependencies (like hello_mraa)
were included in iot-testfiles.intel-corei7-64.tar.gz (I checked).
The same changes should also work with current master (untested, to be
tested by the PR's test build), hence this PR. Remember to check
manually that iot-testfiles.intel-corei7-64.tar.gz for the test build
contains hello_mraa!
> avoid hacks related to test export

- lib/oeqa/runtime/bsp/edison.py
check the edison kernel version upgrade to 3.10.98
> bsp/edison.py: add the FVT for IOTOS-1463

- lib/oeqa/utils/case_interface.py
case developer can inherit this interface to run some non-pyunit test cases, and add them to the report
[IOTOS-1452]
Signed-off-by: zjh <junhuix.zhang@intel.com>
> meta-iotqa: add case_interface in utils

- lib/oeqa/runtime/nodejs/rest_apis.py
Remove the source code after run tests
Related to: IOTOS-1446
> [restapi] Kill the ocserver after run tests

- lib/oeqa/runtime/wifi/comm_wifi_connect.py
- lib/oeqa/runtime/wifi/files/wifi_connect.exp
- lib/oeqa/runtime/wifi/files/wifi_hidden_connect.exp
- lib/oeqa/runtime/wifi/wifi.py
Although WiFi feature does not ask, the 802.11ac (5GHz) WiFi AP and
old WEP encryption are commonly used by user. Desgin 2 cases to
test them.
Add another 1 case to check WiFi password remember function. When
doing second time connection, it does not need to input password.
>  wifi: add three EFT cases to check 802.11ac and WEP encryption

- lib/oeqa/runtime/security/dac_config.py
Previously the error message to be searched for was somewhat vague,
and could be seen in other contexts (eg: ssh error).
> dac_config.py: search for more specific error message

- lib/oeqa/runtime/soletta/soletta_dev_app.py
In the build 423, the "ps" command does not support option "-ef".
So the soletta_dev_app auto cases are FAIL.
Submit patch to change the ps usage in code.
> soletta/soletta_dev_app.py: fix the issue on build #423

- lib/oeqa/runtime/nodejs/rest_apis.py
- The feature about api/oic/p will support in a new separate requirement(IOTOS-1490), but not in 1.0
Releate to: IOTOS-1184
> [restapi] Remove tests about api/oic/p

- conf/test/can.manifest
- conf/test/manual.csv
- lib/oeqa/runtime/can/can.py
- lib/oeqa/runtime/can/comm_can_basic.py
can-bus was supported before M2, at that time we have manual cases.
Now, the two manual cases are automated.
1st is to enable can0 interface in ifconfig.
2nd is to send data to can-bus.
> can: automate 2 FVT cases

- conf/test/bsp.manifest
- lib/oeqa/runtime/bsp/kernel_check.py
Add an auto case for checking kernel version (IOTOS-1428).
This case is for checking intel-quark and intel-corei7-64 images
> bsp/kernel_check.py: add case for IOTOS-1428

- lib/oeqa/runtime/ethernet/comm_ethernet.py
- lib/oeqa/runtime/ethernet/files/config.ini
IOTOS-1419, automatically detect Host ethernet interface for IoT
IOTOS-1494, some scenario although device is not connected, case
still passes unexpectedly. It is due to get_ipv6() has no checking.
Add a non-blank checking to the function when return.
> ethernet: fix case bugs IOTOS-1419 and IOTOS-1494

- lib/oeqa/runtime/nodejs/soletta_setup_test_env_device.py
- The type of old case name is unicode, but the oeruntime expected is string
> [nodejs] Update subcase name

- lib/oeqa/runtime/pythonruntime/apprt_python_runtime.py
Change python runtime case folder name, for there is another python.py
Fix bug IOTOS-1413, to remove SKIP results from python-runtime.log
> python: change folder name from python to pythonruntime

- conf/test/iotivity.manifest
- conf/test/wifi.manifest
- conf/test/zigbee.manifest
- lib/oeqa/runtime/bluetooth/bluetooth.py
- lib/oeqa/runtime/bluetooth/comm_bt_6lowpan.py
- lib/oeqa/runtime/bluetooth/comm_bt_6lowpan_mnode.py
- lib/oeqa/runtime/bluetooth/comm_bt_command_mnode.py
Besides fullauto and iottest (sanity) manifest, we need to ensure
individual domain manifest has all cases. So, add them into the
domain.manifest files. Fix typo class name in Bluetooth domain, which
would make some case missed in final result.
> comms: put all the newly adding cases into individual manifest

- lib/oeqa/runtime/bluetooth/files/target_ssh.exp
- lib/oeqa/runtime/wifi/files/ssh_to.exp
- lib/oeqa/runtime/wifi/wifi.py
In 2 BT and 2 WiFi cases, we need to do ssh to another device. The
expect file has "Host key verification failed." error, fix it by
adding 400 mode to ssh_key file and changing expect steps.
> wifi and bluetooth: fix bug for doing ssh on IoT target

- conf/test/utils/test_gplv3_free_image.sh
previously, it use "grep -w" to filter the violated package name.
however, this will skip some component for example libreadline6
(the component name in license web page is "readline"), which is
GPLv3 violated.
remove "grep -w" will increase the efforts of manual check.
[skip-ci]
> test_gplv3_free_image.sh

- conf/test/python.manifest
weeks ago, the python folder name was changed to pythonruntime,
only the fulltest.manifest files were modified. Now, modify the
python.manifest.
> python: modify python.manifest to work for new case folder name

- recipes-test/ble-tool/bluez5_%.bbappend
- recipes-test/systemd/systemd_%.bbappend
@testkit: please review soon, the problem with Bluez is preventing
the update to recent OE-core master.
> bluez5, systemd: avoid assumptions about build dir

- recipes-test/openmp-app/openmp-app.bb
- recipes-test/openmp-app/openmp-app/openmp-app.c
This builds a small test application to test functionality of gcc's
OpenMP support.
Signed-off-by: Jussi Laako <jussi.laako@linux.intel.com>
> Add test app for gcc OpenMP feature

- lib/oeqa/runtime/iotivity/files/group_client.exp
- lib/oeqa/runtime/iotivity/iotvt_integration.py
- lib/oeqa/runtime/iotivity/iotvt_integration_mnode.py
- lib/oeqa/runtime/iotivity/iotvt_wifi.py
As iotivity version update, some output string of example apps will
change. So if the cases check too many unnessesary strings, they
would meet failure but not bug. Adjust checking conditions to improve
case stability.
> iotivity: change some judgement for iotivity cases

- lib/oeqa/runtime/bluetooth/bluetooth.py
- lib/oeqa/runtime/bluetooth/comm_bt_command_mnode.py
- lib/oeqa/runtime/ethernet/comm_ethernet.py
- lib/oeqa/runtime/iotivity/files/group_client.exp
- lib/oeqa/runtime/iotivity/iotvt_integration.py
- lib/oeqa/runtime/iotivity/iotvt_integration_mnode.py
- lib/oeqa/runtime/iotivity/iotvt_wifi.py
- lib/oeqa/runtime/wifi/comm_wifi_connect.py
- lib/oeqa/runtime/wifi/comm_wifi_mnode.py
- lib/oeqa/runtime/wifi/files/config.ini
- lib/oeqa/runtime/wifi/wifi.py
Add more trial for comms domain:
Enlarge iotivity/groupclient working time from 10s to 30s.
Add file existance check for iotivity/roomclient.
Add -s option support in Ethernet case to get Host interface.
Modify WiFi/big_file creation to be under /home/root folder.
Enable WiFi/internet url to be configured in config.ini.
Enable 3 trial from services scan when WiFi connection failure.
Enable 3 trial for Bluetooth 6lowpan if bt0 is not initialized.
Enable 3 trial for BT BLE scan if it fails.
> comms: improve stability for BT/WiFi/Ethernet/Iotivity

- conf/test/manual-gt.csv
In manual-gt.cvs, add two manual cases to check realsense driver and
its basic usage to show camera preview streaming.
> realsense: add 2 manual cases for realsense checking

- lib/oeqa/runtime/zigbee/comm_zigbee_basic.py
- lib/oeqa/runtime/zigbee/comm_zigbee_cc2520.py
- lib/oeqa/runtime/zigbee/comm_zigbee_mnode.py
- lib/oeqa/runtime/zigbee/zigbee.py
To fix IOTOS-1540, add zigbee module removement functions. When
runninf atmel cases it will remove cc2520 module and after case
done it also removes atmel modules. Same to the opposite.
[skip-ci]
> zigbee: add module remove functions for both atmel and cc2520

- conf/test/soletta.manifest
Considering Soletta-dev-app build error will be fixed
in Ostro 1.3 (IOTOS-1543). Remove relative cases in
current test execution plan.
[skip-ci]
> soletta.manifest: remove soletta-dev-app test plan

- conf/test/manual-1.csv
Install image to eMMC when boot from USB stick, and run sanity to check
the image is bootable and functional basically.
[skip-ci]
Signed-off-by: Shen Cathy <cathy.shen@intel.com>
>  manual-1.csv: add one FVT case for IOTOS-1620

- classes/test-iot.bbclass
"except Foo, ex" is no longer supported in Python3. "except Foo as ex" works
in both Python2 and Python3.
Merging this is urgent. It will block automatic upstream updates (see
https://github.com/ostroproject/ostro-os/pull/116).
> test-iot.bbclass: Python3 compatibility

- lib/oeqa/runtime/nodejs/files/restapis/nodeunit_test_api_oic_d.js
- lib/oeqa/runtime/nodejs/files/restapis/nodeunit_test_api_oic_p.js
- lib/oeqa/runtime/nodejs/files/restapis/nodeunit_test_api_oic_res.js
- lib/oeqa/runtime/nodejs/files/restapis/nodeunit_test_api_system.js
- lib/oeqa/runtime/nodejs/rest_apis.py
- Check the server whether start before issue the request
- Stop the server after run test over
- Add node module path for js coverage script
> Update restapi test scripts for enable restapi server before run tests

- lib/oeqa/runtime/nodejs/rest_apis.py
- These tests can be run normally with both python2 and python3.
> Update restapiserver tests to compatible with python2.x and python3

- lib/oeqa/runtime/bluetooth/comm_bt_6lowpan.py
- lib/oeqa/runtime/bluetooth/comm_bt_6lowpan_mnode.py
- lib/oeqa/runtime/bluetooth/comm_bt_command.py
- lib/oeqa/runtime/bluetooth/comm_bt_command_mnode.py
- lib/oeqa/runtime/bluetooth/comm_bt_stability.py
- lib/oeqa/runtime/sanity/comm_wifi_connect.py
To adopt python3 execution, update corresponding BT and wifi TCs.
[skip-ci]
> update bluetooth and wifi TCs for python3

- lib/oeqa/runtime/bluetooth/bluetooth.py
- lib/oeqa/runtime/bluetooth/comm_bt_command_mnode.py
- lib/oeqa/runtime/ethernet/comm_ethernet.py
- lib/oeqa/runtime/iotivity/iotvt_integration.py
- lib/oeqa/runtime/iotivity/iotvt_integration_mnode.py
- lib/oeqa/runtime/wifi/wifi.py
1. update error output to string from bytes
2. fix wifi TC to handle when multi services match single ssid
[skip-ci]
Signed-off-by: yma11 <yan.ma@intel.com>
> update comms TCs to give correct format of error logs for python3

- lib/oeqa/runtime/iotivity/iotvt_integration.py
- lib/oeqa/runtime/sanity/iotivity.py
We are tightening overall ip6tables firewall settings. Make holes to the firewall so that the Iotivity tests can succeed. Since Iotivity opens a random unicast listening port, we need to open all "ephemeral" ports for link-local access. After this PR is merged https://github.com/ostroproject/meta-ostro/pull/249 can pass the tests.
> iotivity: open holes to IPv6 firewall.

- recipes-test/hello-bundle-a/hello-bundle-a.bb
- recipes-test/hello-bundle-b/hello-bundle-b.bb
- recipes-test/hello-bundle-s/hello-bundle-s.bb
- recipes-test/hello/hello.bb
- recipes-test/mraa-test/mraa-test_1.0.0.bb
- recipes-test/openmp-app/openmp-app.bb
- recipes-test/read-map/read-map_1.0.0.0.bb
- recipes-test/shm-util/shm-util_1.0.0.0.bb
After a change in openembedded-core, we're now getting more accurate information
about components that do not properly use the build system LDFLAGS in linking.
See http://git.yoctoproject.org/cgit.cgi/poky/commit/?id=a98a8180863ff45b477a1f8439ebcec21151d282
The test utils in recipes-test do not seem to use ${LDFLAGS} and
we're hit by a package QA test error.
Add ${LDFLAGS} to get rid of the failure.
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>
> recipes-test: fix "ldflags" package QA test for test utils

- lib/oeqa/runtime/nodejs/files/restapis/nodeunit_test_api_oic_d.js
- lib/oeqa/runtime/nodejs/files/restapis/nodeunit_test_api_oic_p.js
- lib/oeqa/runtime/nodejs/files/restapis/nodeunit_test_api_oic_res.js
- lib/oeqa/runtime/nodejs/files/restapis/nodeunit_test_api_system.js
- lib/oeqa/runtime/nodejs/rest_apis.py
- Fix the nodeunit dependencies issue.
- Open 5683 port before running test cases to avoid the REST APIs
return an empty array value when discoverying devices or resources.
- Enable the test cases for /api/oic/p
Signed-off-by: Zhong Qiu zhongx.qiu@intel.com
> [rest-apis] Update the REST API test cases.
