lib/oeqa/runtime/sanity/apprt_java.py
lib/oeqa/runtime/sanity/apprt_python.py

Add tag to sanity apprt_java cases.
Add tag to sanity apprt_python cases.

apprt: add FeatureID and TestType tags to Python and Java sanity cases

---

lib/runtest.py

Reverts ostroproject/meta-iotqa#4, wrongly merged it but be intent to merge PR/#9.

Revert "meta-iotqa: a work around methods to fit upstream changes"

---

recipes-core/packagegroups/packagegroup-qa-tests.bb

Use this packagroup to add some apps in image.

meta-iotqa: Add packageroup for qatests

---

conf/test/stability.manifest
lib/oeqa/runtime/bluetooth/bluetooth.py
lib/oeqa/runtime/bluetooth/comm_bt_stability.py
lib/oeqa/runtime/bluetooth/files/discoverable_off.exp
lib/oeqa/runtime/bluetooth/files/power_off.exp
lib/oeqa/runtime/wifi/comm_wifi_stability.py
lib/oeqa/runtime/wifi/wifi.py

Add three cases, enable/disable wifi for 200 times
power on/off bluetooth for 200 times
turn on/off bluetooth visibility for 200 times

comms: add 3 stability cases for WiFi and Bluetooth

---

conf/test/security.manifest
lib/oeqa/runtime/security/openssl.py

Add openssl test based on ptest, which should be already enabled
in the image.

security tests: add openssl test

---

conf/test/manual.csv
lib/oeqa/runtime/sanity/baseos.py

1. Clean up the document cases according to NoNeedQA review and revisit document requirements
2. 5 sanity baseos case need to add feature ID in code

Update test case according to  test restropection:

---

lib/runtest.py

meta-iotqa: support multi-node for ostro qa

---

lib/oeqa/runtime/nodejs/apprt_nodejs_runtime.py
lib/oeqa/runtime/nodejs/apprt_nodejs_runtime_log_parser.py
lib/oeqa/runtime/nodejs/iotivity_js_apis.py
lib/oeqa/runtime/nodejs/rest_apis.py

Using the command tar to replace unzip
Remove .gz in test scripts
Related to: IOTOS-1417

[nodejs] Update the format tar.gz and zip package to tar

---

lib/oeqa/utils/helper.py

meta-iotqa: add some linux account manage api in helper.py

---

lib/oeqa/runtime/nodejs/apprt_nodejs_runtime.py
lib/oeqa/runtime/nodejs/apprt_nodejs_runtime_log_parser.py

Update test cases number
Related to: IOTOS-1416

[nodejs] Fix issue that nodejs test cases run fail

---

lib/oeqa/runtime/nodejs/files/restapis/nodeunit_test_api_oic_d.js
lib/oeqa/runtime/nodejs/rest_apis.py

Remove trailing spaces.
Update scripts for get response resource.
Related to: IOTOS-1343

[restapi] Add scripts to launch ocserver

---

conf/test/stability.manifest
lib/oeqa/runtime/sensor/EnvirSetup.py
lib/oeqa/runtime/sensor/config/sol-flow-intel-galileo-rev-g.json
lib/oeqa/runtime/sensor/config/sol-flow-intel-minnow-max-linux_gt_3_17.json
lib/oeqa/runtime/sensor/config/workload.sh
lib/oeqa/runtime/sensor/test_gyro_mpu6050_4_hrs.py
lib/oeqa/runtime/sensor/test_light_tsl2561_4_hrs.py
lib/oeqa/runtime/sensor/test_sensor_with_tar_untar_task.py

TCs: test_gyro_mpu6050_4_hrs.py, test_light_tsl2561_4_hrs.py, test_sensor_with_tar_untar_task.py
For each TC, it will firstly do environment setup(sensor initializing, test app generate),
then execute the fbp file on target and verify the output
Signed-off-by: ma yan <yan.ma@intel.com>

stability: add sensor related stability TCs

---

conf/test/stability.manifest
lib/oeqa/runtime/soletta/files/soletta-stability.fbp
lib/oeqa/runtime/soletta/soletta_stability.py

add soletta stabilty test case: run multiple nodes concurrently in 30 mins
and update relevant stability.manifest

Soletta stabilty case

---

lib/oeqa/runtime/soletta/soletta_stability.py

fix the bug: adjust create folder success and raise assert

soletta_stability.py: fix the test setup bug

---

lib/oeqa/runtime/sensor/test_gyro_mpu6050_4_hrs.py
lib/oeqa/runtime/sensor/test_light_tsl2561_4_hrs.py
lib/oeqa/runtime/sensor/test_sensor_with_tar_untar_task.py

need to cd :/targetfolder first before execute fbp file. or it will fail to find the correct json file.
Signed-off-by: ma yan <yan.ma@intel.com>

stability: update fbp execute command to fix json locating issue

---

lib/oeqa/runtime/nodejs/apprt_nodejs_runtime.py

[nodejs]Replace tar.gz to tar

---

conf/test/manual.csv

According to comments in IOTSOS-401, the system log means the system
log "jounalctl". So update test case to check systemd log.

manual.csv: update test case for IOTOS-401

---

conf/test/galileo.iottest.manifest
conf/test/iottest.manifest
conf/test/minnowmax.iottest.manifest
lib/oeqa/runtime/sanity/apprt_iotivity_node.py
lib/oeqa/runtime/sanity/apprt_restapi.py
lib/oeqa/runtime/sanity/files/apprt_test_iotivity_node.js

[sanity] Add two sanity tests for restapi and iotivity-node

---

conf/test/iotivitynode.manifest
lib/oeqa/runtime/nodejs/iotivity_node_upstream.py
lib/oeqa/runtime/nodejs/iotivity_node_upstream_parser_log.py

Setup test environment for tests on device
Run tests via oeruntime
Parse the result log

[iotivity-node] Import tests from upstream

---

conf/test/security.manifest
lib/oeqa/runtime/security/app_data_protection.py

app_data_protection.py checks the permissions of the manifest and
other relevant files for the example-app-c and example-app-node
applications.

security test: add app data protection test

---

lib/oeqa/runtime/sensor/EnvirSetup.py
lib/oeqa/runtime/sensor/config/sol-flow-intel-edison-rev-c.json
lib/oeqa/runtime/sensor/config/sol-flow-intel-galileo-rev-g.json
lib/oeqa/runtime/sensor/test_adc_ads7955.py
lib/oeqa/runtime/sensor/test_adc_int3495.py
lib/oeqa/runtime/sensor/test_gyro_mpu6050_4_hrs.py
lib/oeqa/runtime/sensor/test_light_tsl2561_4_hrs.py
lib/oeqa/runtime/sensor/test_sensor_with_high_cpu_consumption.py

1. sanity for Edison: test_adc_ads7955
2. sanity for Galileo: test_adc_int3495
3. update stability TCs: modify setup and add tear down
Signed-off-by: ma yan <yan.ma@intel.com>

sensor sanity: add 2 sanity TCs and update previous stability TCs

---

lib/oeqa/runtime/soletta/soletta_auto.py

Add 195 soletta upsteram fbp test cases into auto test framework

soletta_auto.py: execute soletta upstream test cases

---

conf/test/solettaplatform.manifest
lib/oeqa/runtime/nodejs/files/solettaplatform/getresult.js
lib/oeqa/runtime/nodejs/get_source.py
lib/oeqa/runtime/nodejs/soletta_platform_service_upstream.py
lib/oeqa/runtime/nodejs/soletta_platform_service_upstream_parser_log.py
lib/oeqa/runtime/nodejs/update_setup_suite_js.py

Setup test environment for tests on device
Run tests via oeruntime
Parse the result log
Related to: IOTOS-1157

[platform-service] Import tests for Soletta Platform Service API

---

lib/oeqa/runtime/wifi/comm_wifi_connect.py
lib/oeqa/runtime/wifi/comm_wifi_mnode.py
lib/oeqa/runtime/wifi/files/config.ini
lib/oeqa/runtime/wifi/files/create_1000_files.sh
lib/oeqa/runtime/wifi/files/ssh_to.exp
lib/oeqa/runtime/wifi/wifi.py

Connect two Ostro devices to the same WiFi AP. Then test:
Device1 ssh to Device2
Device1 scp a file to Device2
Stability Device1 scp 1000 small files to Device2
Stability Device1 scp a big file (500M) to Device2
Stability after half an hour, check if WiFi connect is still available (by ssh_to)

wifi: add 5 multiple nodes WiFi test cases

---

lib/oeqa/runtime/nodejs/get_source.py
lib/oeqa/runtime/nodejs/iotivity_node_upstream.py

[iotivity-node] Update test script to download source code

---

conf/test/gpio.manifest
lib/oeqa/runtime/nodejs/soletta_gpio_api_upstream.py
lib/oeqa/runtime/nodejs/soletta_setup_test_env_device.py
lib/oeqa/runtime/nodejs/update_suite_js.py

Setup test environment for tests on device
Run tests via oeruntime
Parse the result log
Releated to: IOTOS-1152

[nodejs] Add FVT for GPIO API

---

conf/test/spi.manifest
lib/oeqa/runtime/nodejs/soletta_spi_api_upstream.py

[nodejs] Add tests for SPI API

---

conf/test/nodejs-i2c.manifest
lib/oeqa/runtime/nodejs/soletta_i2c_api_upstream.py

[nodejs] Add FVT for I2C API

---

conf/test/nodejs-uart.manifest
lib/oeqa/runtime/nodejs/soletta_uart_api_upstream.py

[nodejs] Add tests for UART API

---

conf/test/nodejs-pwm.manifest
lib/oeqa/runtime/nodejs/soletta_pwm_api_upstream.py

[nodejs] Add FVT for PWM API

---

lib/oeqa/utils/case_interface.py

raise error when have exception in case_interface's testmethod, this helps
case developer to debug those upstream cases.
code clean, remove some duplicate code
add casename.strip() , This has included https://github.com/ostroproject/meta-iotqa/pull/95
Signed-off-by: zjh <junhuix.zhang@intel.com>

meta-iotqa: raise error when have exception in case_interface's testmethod

---

lib/oeqa/runtime/nodejs/iotivity_node_upstream.py

[iotivity-node] Format result log file name

---

conf/test/manual.csv

Related to: IOTOS-1160/1161
[skip-ci]

[soletta] Add FVT for mqtt and coap

---

lib/oeqa/runtime/appfw/test_appfw.py

1. suitable for ps command
2. add more check for user account
3. add more check for app running in container
Signed-off-by: Wu Dawei <daweix.wu@intel.com>

appfw/test_appfw.py: optimize cases

---

lib/oeqa/runtime/sensor/config/sol-flow-intel-minnow-max-linux_gt_3_17.json

update the sensor configuration typo
Fixing IOTOS-1524.
[skip-ci]

sensor minnow configuratin:

---

lib/baserunner/baserunner.py
lib/gen_manifest.py

List all components:
./gen_manifest.py --list
gen some components' manifest:
./gen_manifest.py -s wifi -s bluetooth
Signed-off-by: zjh <junhuix.zhang@intel.com>

meta-iotqa: add components feature to gen_manifest

---

recipes-test/appfw-test-app/files/manifest
recipes-test/appfw-test-app/files/wrapperapp

1. Fix app launch issue
2. Modify script to test App extra environment variables

recipes-test/appfw-test-app: Update App

---

lib/oeqa/runtime/sanity/baseos.py

Ignore the 'GPT' errors since it's harmless.

sanity/baseos.py : Add one case to check systemd boot errors

---

lib/oeqa/runtime/nodejs/iotivity_node_upstream.py

[iotivity-node]Update initial path for results log

---

lib/oeqa/runtime/nodejs/README.md
lib/oeqa/runtime/nodejs/get_source.py
lib/oeqa/runtime/nodejs/iotivity_node_upstream.py

Update iotivity-node test scripts for add test branch

---

conf/test/manual-1.csv

Checking kernel's .config file for CONFIG_TCG_TPM and CONFIG_TCG_TIS
Case owner: alexandru.cornea@intel.com
[skip ci]

manual-1.csv: added TPM test

---

conf/test/manual-1.csv

Add 1 test case for IOTOS-1504: check opencl integraiton
[skip-ci]

manual-1.csv

---

lib/runtest.py

change parameters number of two method to fit the changes of upstream

change parameters number of two method to fit the changes of upstream

---

conf/test/manual-1.csv

Add three cases for ROS, temporarily put them in design
status, because the ROS is not integrated into image yet.
[skip-ci]

manual-1.csv: add 3 FTV manual cases for ROS

---

lib/oeqa/runtime/nodejs/files/iotivityjsapis/test_oic_client.js
lib/oeqa/runtime/nodejs/files/iotivityjsapis/test_oic_device.js
lib/oeqa/runtime/nodejs/files/iotivityjsapis/test_oic_discovery.js
lib/oeqa/runtime/nodejs/files/iotivityjsapis/test_oic_platform.js
lib/oeqa/runtime/nodejs/files/iotivityjsapis/test_oic_presence.js
lib/oeqa/runtime/nodejs/files/iotivityjsapis/test_oic_server.js
lib/oeqa/runtime/nodejs/iotivity_js_apis.py

Update tests for iotivity-node

---

conf/test/iotivitynode.manifest
conf/test/iotivitynode.upstream.manifest

Move iotivity-node upstream tests to a new manifest file

---

conf/test/manual-1.csv

Since image has no VC-1 gst plugin support, changed the
relative case to "design" status.
Will revisit the case after milestone release.
[skip-ci]

manual-1.csv: update VC-1 case to design

---

lib/oeqa/runtime/nodejs/iotivity_js_apis.py

- Update test script for iotivity-node to make sure the tests can get correct results on Galileo

Update test script for iotivity-node

---

conf/test/manual-1.csv

1. update opencl integration case
2. add opencl app build/exec case
[skip-ci]

manual-1.csv: update opencl case

---

lib/oeqa/runtime/nodejs/get_source.py
lib/oeqa/runtime/nodejs/iotivity_js_apis.py

Update the filter condition to kill test process

---

lib/oeqa/runtime/nodejs/files/iotivityjsapis/test_oic_server.js
lib/oeqa/runtime/nodejs/iotivity_js_apis.py

- The two methods has been renamed in spec.

Rename two methods of interface oicServer for iotivity-node

---

lib/oeqa/runtime/sanity/apprt_restapi.py

Add some conditions to check the restapi server

---

conf/test/manual-1.csv

stress is not integrated in image,so need to local build image to test it
[skip ci]
Signed-off-by: Wu Dawei <daweix.wu@intel.com>

conf/test/manual-1.csv: modify manual case for Stress benchmark

---

lib/oeqa/runtime/sanity/apprt_restapi.py

- Check the server whether start before issue the request
- Stop the server after run test over

Update test script for enable the restapi server

---

lib/oeqa/runtime/nodejs/get_source.py
lib/oeqa/runtime/nodejs/iotivity_node_upstream.py

- These tests can be run normally with both python2 and python3.

Update iotivity-node test scripts to compatible with python2.x and python3

---

conf/test/manual-1.csv

check thermal deamon(v1.5.3) launched in system.
[related-to] IOTOS-1675
[skip-ci]
Signed-off-by: yma11 <yan.ma@intel.com>

Add TC for thermal deamon check

---

conf/test/manual-1.csv

[skip ci]
Signed-off-by: Wu Dawei <daweix.wu@intel.com>

manual-1.csv: Add requirement verification case for IOTOS-1634

---

lib/oeqa/runtime/nodejs/coap.py
lib/oeqa/runtime/nodejs/files/coap/coap.js
lib/oeqa/runtime/nodejs/files/mqtt/mqtt.js
lib/oeqa/runtime/nodejs/mqtt.py

Add TCs for MQTT and Coap

---

classes/test-iot.bbclass

Please review. Can be merged once test build
https://github.com/ostroproject/ostro-os/pull/144 =
https://ostroproject.org/jenkins/job/ostro-os_pull-requests/994/
confirms that this really works.

Python3 test export

---

lib/oeqa/runtime/security/firewall_rules.py

Signed-off-by: Wu Dawei <daweix.wu@intel.com>

security/firewall_rules.py : update cases for python3

---

lib/oeqa/utils/case_interface.py

case_interface: A walk around method to genrate correct logs

case_interface: A walk around method to genrate correct logs

---

lib/oeqa/runtime/bluetooth/bluetooth.py
lib/oeqa/runtime/bluetooth/comm_bt_command.py
lib/oeqa/runtime/bluetooth/comm_bt_command_mnode.py
lib/oeqa/runtime/ethernet/comm_ethernet.py
lib/oeqa/runtime/iotivity/iotvt_integration.py
lib/oeqa/runtime/iotivity/iotvt_integration_mnode.py
lib/oeqa/runtime/wifi/wifi.py

Add judgement before apply ascii decode to output of shell_cmd_timeout()
[related-to] IOTOS-1678
[skip-ci]
Signed-off-by: yma11 <yan.ma@intel.com>

update comms TCs for python3

---

lib/oeqa/runtime/nodejs/iotivity_node_get_version_package_file.py
lib/oeqa/runtime/nodejs/iotivity_node_upstream.py

- Add file for getting iotivity-node version
- Fix print error

Add file for getting iotivity-node version

---

lib/oeqa/runtime/nodejs/iotivity_node_upstream.py

- The failed tests which effected by firewall can be passed on Galileo

Add firewall setting for iotivity-node tests

---

OstroTestExecution.rst

Add document about test execution.
How to document about test environment set up and test execution.
Signed-off-by: Shen, Cathy <cathy.shen@intel.com>

Add document about test execution
